<?php
/**
 * @file
 * Install, update and uninstall functions for the GSB Academic Year module.
 */

/**
 * Implements hook_install().
 */
function gsb_twelve_twenty_install() {
}

/**
 * Implements hook_uninstall().
 */
function gsb_twelve_twenty_uninstall() {

 // Delete variables.
  variable_del('twelve_twenty_token');
  variable_del('twelve_twenty_token_auth_url');
  variable_del('twelve_twenty_token_ret_url');
}
